project:
  type: website
  output-dir: docs

website:
  title: "Posts"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/sarahramboyong/
      - icon: github
        text: Github
        href: https://github.com/sarahramboyong
      - icon: github
        text: Github
        href: https://git.cs.vt.edu/sarahrambo



format:
  html:
    theme: yeti
    css: styles.css



